// ─── orchestration/agentData.ts ───────────────────────────────────────────────
// Static data: signal nodes, foundation agents, operational agents, governance agents.

import type { AgentNode, GovernanceAgent } from './types';

export const SIGNAL_NODES = [
  { id: 'sig-auth', label: 'AUTH_EXPIRY', sublabel: 'HIGH', color: '#f59e0b' },
  { id: 'sig-care', label: 'CARE_GAP', sublabel: 'HIGH', color: '#ef4444' },
  { id: 'sig-behav', label: 'BEHAVIORAL', sublabel: 'MEDIUM', color: '#42be65' },
];

export const FOUNDATION_AGENTS: AgentNode[] = [
  {
    id: 'graph-intel',
    label: 'Graph Intelligence',
    sublabel: 'T+0',
    color: '#78a9ff',
    completionTime: 'T+0',
    completionMin: 0,
    fetchSystems: [{ id: 'neo4j', label: 'Neo4j', sublabel: 'Knowledge Graph', side: 'fetch', payloadKey: 'graph_intel_push' }],
    pushSystems: [{ id: 'orch-ctx', label: 'Orchestration', sublabel: 'Context', side: 'push', payloadKey: 'graph_intel_push' }],
    tier: 'Tier 1 — Foundation',
    rationale: "Maria's 21-node subgraph assembled from Neo4j. Resolved caregiver relationship to Elena, dependent relationship to Sophia, and active postpartum episode context. Identity confidence 97% — golden record committed. Graph context package injected into orchestration context for all downstream agents.",
    outcome: 'Context package ORCHESTRATION_CONTEXT_001 assembled. 21 nodes, 26 edges. Caregiver + dependent relationships resolved. Duplicate therapy edge flagged.',
    confidence: 0.97,
  },
  {
    id: 'identity',
    label: 'Identity Resolution',
    sublabel: 'T+0',
    color: '#0C55B8',
    completionTime: 'T+0',
    completionMin: 0,
    fetchSystems: [{ id: 'cdp', label: 'CDP', sublabel: '4 Source Systems', side: 'fetch', payloadKey: 'identity_push' }],
    pushSystems: [{ id: 'golden', label: 'Golden Record', sublabel: 'MARIA_SD_001', side: 'push', payloadKey: 'identity_push' }],
    tier: 'Tier 1 — Foundation',
    rationale: 'Four source systems (Claims, EHR, Auth, RHTP) returned conflicting identity records for Maria. Deterministic matching on SSN hash + DOB resolved 3 conflicts. Claims designated as authoritative source per survivorship rules. Golden record GR_MARIA_SD_001 committed.',
    outcome: 'Golden record GR_MARIA_SD_001 committed. 4 sources reconciled, 3 conflicts resolved. Identity confidence 97%. Authoritative source: Claims.',
    confidence: 0.97,
  },
  {
    id: 'consent',
    label: 'Consent Agent',
    sublabel: 'T+0',
    color: '#42be65',
    completionTime: 'T+0',
    completionMin: 0,
    fetchSystems: [{ id: 'consent-store', label: 'Consent Store', sublabel: 'Proxy Scope', side: 'fetch', payloadKey: 'consent_push' }],
    pushSystems: [{ id: 'consent-gate', label: 'Consent Gate', sublabel: 'OPEN', side: 'push', payloadKey: 'consent_push' }],
    tier: 'Tier 1 — Foundation',
    rationale: "Consent store queried for Maria's active consent records across all domains. Full TPO consent confirmed for primary care coordination. Proxy consent from Elena Redhawk validated — scope limited to MEDICATION_MGMT and APPT_COORDINATION. Consent gate opened for orchestration to proceed.",
    outcome: 'Consent gate OPEN. Full TPO consent confirmed. Proxy consent for Elena validated (limited scope). Martin Pharmacy domain flagged as LIMITED — fill history only.',
    confidence: 0.99,
  },
  {
    id: 'person-state',
    label: 'Person State Intel',
    sublabel: 'T+0',
    color: '#06b6d4',
    completionTime: 'T+0',
    completionMin: 0,
    fetchSystems: [{ id: 'engage-platform', label: 'Engagement', sublabel: 'Behavioral Signals', side: 'fetch', payloadKey: 'person_state_push' }],
    pushSystems: [{ id: 'state-profile', label: 'State Profile', sublabel: 'Receptivity: 87%', side: 'push', payloadKey: 'person_state_push' }],
    tier: 'Tier 1 — Foundation',
    rationale: "Behavioral signals from engagement platform analyzed. 3 portal logins this week indicates ENGAGED state. Communication fatigue assessed as LOW — no recent outreach saturation. Caregiver stress signals elevated from Sophia's care gap activity. Recommended channel: Portal. Optimal timing: 10am peak engagement window.",
    outcome: 'State profile assembled. Behavioral state: ENGAGED. Receptivity score: 87%. Recommended channel: Portal at 10am. Caregiver stress flag: ELEVATED.',
    confidence: 0.87,
  },
];

export const OPERATIONAL_AGENTS: AgentNode[] = [
  {
    id: 'care',
    label: 'Clinical Care Agent',
    sublabel: 'T+3→8m',
    color: '#0C55B8',
    completionTime: 'T+8m',
    completionMin: 8,
    fetchSystems: [{ id: 'ehr', label: 'EHR', sublabel: 'Clinical Records', side: 'fetch', payloadKey: 'care_push' }],
    pushSystems: [
      { id: 'auth-sys', label: 'Auth System', sublabel: 'Evidence Package', side: 'push', payloadKey: 'care_push' },
      { id: 'h1ab', label: 'H1ab', sublabel: 'Sarah Johnson — enriched', side: 'push', payloadKey: 'h1ab_push' },
      { id: 'dr-chen-ehr', label: 'Bennett County Health EHR', sublabel: 'CDS Hook · FHIR R4 ✓', side: 'push', payloadKey: 'dr_chen_cds_hook' },
      { id: 'rally-mobile', label: 'RHTP Mobile', sublabel: 'Maria — widget push ✓', side: 'push', payloadKey: 'rhtp_mobile_push' },
      { id: 'optumrx-gate', label: 'Martin Pharmacy ⚠', sublabel: 'CONSENT GATE', side: 'push', payloadKey: 'policy_intercept_pharmacy' },
    ],
    tier: 'Tier 2 — Operational',
    rationale: 'CAREGAP_HBA1C expiring in 4 days for HbA1c lab order. EHR records fetched — 3 supporting clinical records assembled. Medical necessity basis confirmed: active postpartum episode Day 427, prior auth history. Evidence package submitted to auth system. H1ab brief enriched with real-time context replacing 47-day-old snapshot. Martin Pharmacy Med review enrollment attempted — blocked by consent domain boundary.',
    outcome: 'CAREGAP_HBA1C renewal evidence submitted. H1ab Sarah Johnson brief updated with real-time context. Martin Pharmacy Med review blocked — consent domain boundary enforced. Auth cycle time: 0.3 days (was 8.2 days).',
    confidence: 0.94,
  },
  {
    id: 'provider',
    label: 'Provider Enablement',
    sublabel: 'T+3→22m',
    color: '#8b5cf6',
    completionTime: 'T+22m',
    completionMin: 22,
    fetchSystems: [{ id: 'registry', label: 'Provider Registry', sublabel: 'NPI Database', side: 'fetch', payloadKey: 'provider_push' }],
    pushSystems: [{ id: 'cred-sys', label: 'Eligibility', sublabel: 'Renewal Initiated', side: 'push', payloadKey: 'provider_push' }],
    tier: 'Tier 2 — Operational',
    rationale: "Bennett County Health (NPI_1234567890) eligibility renewal deadline detected: 21 days. 12 active episodes under Bennett County Health's care would be disrupted if eligibility lapses. Proactive renewal initiated with Bennett County Health eligibility system. No human intervention required — fully automated renewal workflow.",
    outcome: 'Eligibility renewal initiated for Bennett County Health. 12 active episodes protected. Renewal deadline: 21 days. Eligibility system ref: CRED_RENEWAL_20241115_001.',
    confidence: 0.91,
  },
  {
    id: 'utilization',
    label: 'Eligibility Mgmt',
    sublabel: 'T+3→8m',
    color: '#06b6d4',
    completionTime: 'T+8m',
    completionMin: 8,
    fetchSystems: [{ id: 'guidelines', label: 'Clinical Guidelines', sublabel: 'SD Medicaid LCD L38779', side: 'fetch', payloadKey: 'utilization_push' }],
    pushSystems: [{ id: 'payer', label: 'Payer System', sublabel: 'Auth Record', side: 'push', payloadKey: 'utilization_push' }],
    tier: 'Tier 2 — Operational',
    rationale: 'SD Medicaid LCD L38779 clinical guideline referenced for HbA1c lab order. Medical necessity criteria met — active postpartum episode with documented prior auth history. Auth record updated in payer system. Cycle time reduced from 8.2 days (manual) to 0.3 days (automated). 96% improvement in processing speed.',
    outcome: 'Auth record updated in payer system. Clinical guideline SD Medicaid LCD L38779 applied. Auth cycle time: 0.3 days (96% improvement vs 8.2 day manual baseline).',
    confidence: 0.96,
  },
  {
    id: 'appeals',
    label: 'Behavioral Health Agent',
    sublabel: 'T+3→31m',
    color: '#f1c21b',
    completionTime: 'T+31m ⚡',
    completionMin: 31,
    intercepted: true,
    interceptLabel: 'HELD — HUMAN REVIEW',
    fetchSystems: [{ id: 'cms-rules', label: 'SD Medicaid Rules', sublabel: 'Regulatory Framework', side: 'fetch', payloadKey: 'appeals_push' }],
    pushSystems: [{ id: 'review-q', label: 'Reviewer Queue', sublabel: 'Dr. K. Patel', side: 'push', payloadKey: 'appeals_push' }],
    tier: 'Tier 2 — Operational',
    rationale: 'Automated appeal dispatch attempted for CAREGAP_HBA1C. Policy Boundary agent intercepted at T+31m — SD Medicaid.APPEAL.AUTO.THRESHOLD.001 triggered. Clinical necessity determination exceeds automated authority threshold. Human reviewer Dr. K. Patel notified. 68-hour regulatory deadline monitored. Context package assembled for reviewer.',
    outcome: 'INTERCEPTED — held for human review. Dr. K. Patel notified. 68-hour deadline monitored. Context package assembled. Policy: SD Medicaid.APPEAL.AUTO.THRESHOLD.001.',
    confidence: 0.78,
  },
  {
    id: 'financial',
    label: 'Financial Intelligence',
    sublabel: 'T+3→15m',
    color: '#10b981',
    completionTime: 'T+15m',
    completionMin: 15,
    fetchSystems: [{ id: 'benefits', label: 'Benefits Engine', sublabel: 'Claims System', side: 'fetch', payloadKey: 'financial_push' }],
    pushSystems: [{ id: 'portal', label: 'Member Portal', sublabel: 'OOP Summary', side: 'push', payloadKey: 'financial_push' }],
    tier: 'Tier 2 — Operational',
    rationale: "Benefits engine queried for Maria's current plan year accumulations. OOP liability calculated for HbA1c lab order given current deductible and OOP max status. Referral to Dr. Sarah Kim initiated. Cost summary pushed to member portal — financial surprise risk eliminated. OOP range: $340–$480.",
    outcome: 'OOP liability range $340–$480 published to member portal. Referral to Dr. Sarah Kim initiated. Financial surprise risk: ELIMINATED. Benefits engine ref: BENEFITS_CALC_20241115_001.',
    confidence: 0.93,
  },
  {
    id: 'caregiver',
    label: 'Caregiver Intelligence',
    sublabel: 'T+3→19m',
    color: '#c084fc',
    completionTime: 'T+19m ⚡',
    completionMin: 19,
    intercepted: true,
    interceptLabel: 'CONSENT BOUNDARY',
    fetchSystems: [{ id: 'med-db', label: 'Medication DB', sublabel: 'Lisinopril Records', side: 'fetch', payloadKey: 'caregiver_push' }],
    pushSystems: [{ id: 'care-coord', label: 'Care Coordinator', sublabel: 'Elena Thread', side: 'push', payloadKey: 'caregiver_push' }],
    tier: 'Tier 2 — Operational',
    rationale: "Elena Redhawk proxy consent scope validated: MEDICATION_MGMT and APPT_COORDINATION only. Agent attempted to share Maria's medication list (including Lisinopril/A1C status) with third-party care coordinator. Consent Enforcement agent intercepted — THIRD_PARTY_DISCLOSURE exceeds proxy scope. A1C monitoring initiated within allowed scope. Lisinopril interaction flagged for Elena's care thread.",
    outcome: "INTERCEPTED — third-party disclosure blocked. A1C monitoring initiated (within scope). Lisinopril interaction flagged. Elena must grant expanded scope for full coordination.",
    confidence: 0.82,
  },
  {
    id: 'finops',
    label: 'FinOps Agent',
    sublabel: 'T+3→47m',
    color: '#f59e0b',
    completionTime: 'T+47m',
    completionMin: 47,
    fetchSystems: [{ id: 'cost-db', label: 'Cost Database', sublabel: 'Benchmark Rates', side: 'fetch', payloadKey: 'finops_push' }],
    pushSystems: [{ id: 'mlr-ledger', label: 'TCOC Ledger', sublabel: 'Cost Capture', side: 'push', payloadKey: 'finops_push' }],
    tier: 'Tier 2 — Operational',
    rationale: 'Full scenario cost capture executed at T+47m after all agent threads resolved. Actual intervention cost $2,650 vs estimated $2,840 (6.7% under budget). Cost avoidance realized: $18,400 (avoided readmission + manual processing costs). TCOC impact: -0.003. Ledger committed to TCOC tracking system.',
    outcome: 'Cost capture complete. Actual: $2,650 (est: $2,840). Cost avoidance: $18,400. TCOC impact: -0.003. Ledger ref: LEDGER_20241115_MARIA_SD_001.',
    confidence: 0.89,
  },
  {
    id: 'quality-risk',
    label: 'Quality & Risk',
    sublabel: 'T+3→12m',
    color: '#f1c21b',
    completionTime: 'T+12m',
    completionMin: 12,
    fetchSystems: [{ id: 'hedis-engine', label: 'SD Medicaid quality Engine', sublabel: 'Quality Measures', side: 'fetch', payloadKey: 'care_push' }],
    pushSystems: [{ id: 'quality-report', label: 'Quality Report', sublabel: 'Gap Status', side: 'push', payloadKey: 'care_push' }],
    tier: 'Tier 2 — Operational',
    rationale: "SD Medicaid quality engine queried for Maria's open quality measure gaps. HbA1c gap open 45 days — Q4 SD Medicaid quality window active, closure deadline approaching. Home lab kit dispatched as transport-barrier-aware alternative to clinic appointment. Gap status updated in quality report. SD Medicaid quality measure closure projected within 14 days.",
    outcome: 'HbA1c care gap addressed. Home lab kit dispatched. SD Medicaid quality measure closure projected in 14 days. Q4 window: ACTIVE. Quality report updated.',
    confidence: 0.88,
  },
];

export const GOVERNANCE_AGENTS: GovernanceAgent[] = [
  {
    id: 'policy',
    label: 'Policy Boundary',
    color: '#f1c21b',
    interceptAt: [31, 19],
    interceptLabel: '⚡ 2 INTERCEPTS',
    payloadKey: 'policy_intercept_appeals',
    tier: 'Tier 3 — Governance',
    rationale: 'Continuous policy evaluation across all agent actions. SD Medicaid.APPEAL.AUTO.THRESHOLD.001 triggered at T+31m — automated appeal dispatch exceeded authority. CONSENT.DOMAIN.BOUNDARY.002 triggered at T+44m — Martin Pharmacy diagnosis code sharing blocked. Both intercepts resolved within regulatory deadlines.',
    outcome: '2 intercepts executed. Appeals held for human review. Martin Pharmacy consent domain boundary enforced. 100% policy compliance maintained.',
    confidence: 1.0,
  },
  {
    id: 'compliance',
    label: 'Compliance & Regulatory',
    color: '#f59e0b',
    payloadKey: 'audit_push',
    tier: 'Tier 3 — Governance',
    rationale: 'Regulatory deadline monitoring active throughout scenario. SD Medicaid prior auth 72-hour deadline tracked for CAREGAP_HBA1C. State-specific mandates verified. HIPAA minimum necessary enforced on all data payloads. No regulatory violations detected across 71 decisions.',
    outcome: 'All regulatory deadlines met. HIPAA minimum necessary enforced. No violations across 71 decisions. SD Medicaid prior auth deadline: ON TRACK.',
    confidence: 1.0,
  },
  {
    id: 'consent-enforce',
    label: 'Consent Enforcement',
    color: '#ef4444',
    interceptAt: [19],
    interceptLabel: '⚡ T+19m',
    payloadKey: 'consent_enforce_push',
    tier: 'Tier 3 — Governance',
    rationale: "Real-time consent state monitoring active for all agent actions. At T+19m, Caregiver Intelligence agent attempted third-party disclosure exceeding Elena's proxy consent scope. Authority revoked for that specific action. Consent state monitoring continued — no further violations. Real-time revocation capability confirmed.",
    outcome: 'Consent boundary enforced at T+19m. Caregiver agent third-party disclosure authority revoked. Consent state monitoring: ACTIVE. Real-time revocation: CAPABLE.',
    confidence: 0.99,
  },
  {
    id: 'data-gov',
    label: 'Data Governance',
    color: '#8b5cf6',
    payloadKey: 'data_gov_push',
    tier: 'Tier 3 — Governance',
    rationale: '47 data payloads inspected across all agent transactions. 12 PII fields masked (SSN, full DOB, full address). Data residency requirements verified for all payloads. HIPAA minimum necessary standard applied — only fields required for each specific action included. No data residency violations.',
    outcome: '47 payloads inspected. 12 PII fields masked. Data residency verified. Minimum necessary enforced. Fields redacted: SSN, DOB_FULL, ADDRESS_FULL.',
    confidence: 1.0,
  },
  {
    id: 'audit',
    label: 'Audit & Explainability',
    color: '#78a9ff',
    payloadKey: 'audit_push',
    tier: 'Tier 3 — Governance',
    rationale: 'Immutable audit ledger maintained throughout scenario. Every agent decision logged with full rationale, timestamp, and member context. 71 total decisions captured. 8 governance checks — all honored. Audit ledger committed to WORM storage. Export-ready for regulatory review.',
    outcome: 'Audit ledger committed. 71 decisions logged. 8/8 governance checks honored. 2 intercepts recorded. Compliance score: 100%. Ledger ref: LEDGER_20241115_MARIA_SD_001.',
    confidence: 1.0,
  },
];
