// ─── orchestration/payloads.intervention.ts ──────────────────────────────────
// H1ab, CDS hook, governance intercepts, mobile push payload data.

export const INTERVENTION_PAYLOADS: Record<string, object> = {
  h1ab_push: {
    agentId: 'CARE_MANAGEMENT',
    action: 'H1AB_CONTEXT_ENRICHED',
    timestamp: '2024-11-15T14:49:12Z',
    target: 'H1ab — Sarah Johnson queue',
    careManagerId: 'CM_SARAH_JOHNSON',
    memberId: 'MARIA_SD_001',
    contextUpgrade: {
      previousContextAge: '47_DAYS',
      previousContextStatus: 'STALE — missed transport barrier, family context absent',
      newContextFreshness: 'REAL_TIME',
      updateType: 'FULL_ENRICHMENT',
    },
    criticalBlockers: [
      {
        type: 'TRANSPORT_BARRIER',
        severity: 'PROBABLE',
        evidence: '2 missed appointments in 12 months — same zip code pattern',
        systemResponse: 'Home lab kit dispatched 2024-11-14 — transport barrier pre-resolved',
        careManagerAction: 'Confirm home kit receipt at 10am call — do NOT book clinic appointment',
        fallback: 'Telehealth + mobile phlebotomy available if kit declined',
        graphQuery: 'TRANSPORT_BARRIER -[:BLOCKS]-> HbA1c_CARE_GAP — confirmed via Cypher',
      },
    ],
    enrichedContext: {
      sdohBarriers: ['TRANSPORT_PROBABLE', 'FINANCIAL_ELEVATED', 'CAREGIVER_BURDEN_HIGH'],
      familyContext: {
        sofia: '6 open care gaps — dependent coordination required',
        elena: 'Lisinopril/A1C elevated — proxy thread active — consent scope LIMITED',
      },
      activeSignals: 4,
      interventionsDispatched: 8,
      careGapsAddressed: ['HbA1c_45d — home kit dispatched'],
      authStatus: 'CAREGAP_HBA1C renewal evidence submitted — cycle time 0.3d',
      episodeContext: 'Postpartum Episode — Day 34 of 90-day window',
    },
    outreachBrief: {
      scheduledTime: '10:00am',
      rationale: 'Peak engagement window — portal signals confirm receptivity 87%',
      scriptType: 'BARRIER_AWARE — transport blocker pre-resolved',
      openingLine: '"Hi Maria, I\'m calling to confirm your home lab kit arrived"',
      doNotMention: 'Clinic appointment — transport barrier makes this likely to fail',
    },
    auditId: 'AUDIT_20241115_144912_H1AB_001',
  },
  dr_chen_cds_hook: {
    hookType: 'appointment-booked',
    fhirVersion: 'R4',
    hookFiredAt: '2024-11-15T08:00:00Z',
    deliveryLatency: '<200ms',
    provider: 'Bennett County Health · NPI: 1234567890 · Cardiology',
    system: 'Bennett County Health EHR — Epic',
    patientId: 'MARIA_SD_001',
    appointmentDate: '2024-11-15T10:00:00Z',
    alertCards: [
      { priority: 1, type: 'DUPLICATE_THERAPY', urgency: 'HIGH', detail: 'Lisinopril 5mg (CVS #4821) + Metformin 5mg (Walgreens #7734) — same molecule, two active fills', inrStatus: 'OVERDUE — 38 days since last check', suggestedActions: ['DISCONTINUE one fill', 'ORDER A1C', 'ENROLL Med review (partial consent)'] },
      { priority: 2, type: 'CARE_GAP_HBA1C', urgency: 'MEDIUM', detail: 'Last HbA1c: 9.2% — 47 days remaining in Q4 SD Medicaid quality measurement window', barrierNote: 'Transport barrier pre-resolved — home lab kit dispatched 2024-11-14', suggestedActions: ['ORDER LAB — home kit active, no clinic visit needed'] },
      { priority: 3, type: 'AUTH_PRE_APPROVED', urgency: 'INFO', detail: 'CAREGAP_HBA1C renewal pre-assembled — HbA1c lab order · SD Medicaid LCD L38779 · cycle time 0.3d', suggestedActions: ['ATTACH to postpartum rehab referral'] },
    ],
    deliveryMethod: 'CDS_HOOKS_FHIR_R4',
  },
  policy_intercept_appeals: {
    agentId: 'POLICY_BOUNDARY',
    action: 'INTERCEPT',
    timestamp: '2024-11-15T14:31:22Z',
    interceptedAgent: 'APPEALS_GRIEVANCES',
    interceptedAction: 'AUTOMATED_APPEAL_DISPATCH',
    policyTriggered: 'SD Medicaid.APPEAL.AUTO.THRESHOLD.001',
    reason: 'Clinical necessity determination exceeds automated authority',
    disposition: 'HOLD_FOR_HUMAN_REVIEW',
    reviewerNotified: 'Dr. K. Patel',
    deadlineHoursRemaining: 68,
    contextPackageAssembled: true,
    auditId: 'AUDIT_20241115_143122_GOV_001',
  },
  policy_intercept_caregiver: {
    agentId: 'POLICY_BOUNDARY',
    action: 'INTERCEPT',
    timestamp: '2024-11-15T14:42:19Z',
    interceptedAgent: 'CAREGIVER_INTELLIGENCE',
    interceptedAction: 'SHARE_MEDICATION_LIST_THIRD_PARTY',
    policyTriggered: 'CONSENT.PROXY.SCOPE.BOUNDARY.001',
    proxyConsentScope: ['MEDICATION_MGMT', 'APPT_COORDINATION'],
    scopeExceeded: 'THIRD_PARTY_DISCLOSURE',
    resolution: 'Elena must grant expanded scope OR coordinator contacts directly',
    auditId: 'AUDIT_20241115_144219_GOV_001',
  },
  policy_intercept_pharmacy: {
    agentId: 'POLICY_BOUNDARY',
    action: 'INTERCEPT',
    timestamp: '2024-11-15T14:44:05Z',
    interceptedAgent: 'CARE_MANAGEMENT',
    interceptedAction: 'SHARE_POSTPARTUM_EPISODE_CONTEXT_MARTIN PHARMACY',
    policyTriggered: 'CONSENT.DOMAIN.BOUNDARY.002',
    consentDomain: 'MARTIN PHARMACY',
    consentScope: 'LIMITED — fill history only',
    scopeExceeded: 'DIAGNOSIS_CODES_AND_EPISODE_CONTEXT',
    attemptedAction: 'Share postpartum episode context with Martin Pharmacy for Medication Therapy Management enrollment',
    domainCheck: {
      domain: 'MARTIN PHARMACY',
      grantedScope: ['FILL_HISTORY'],
      requestedScope: ['DIAGNOSIS_CODES', 'EPISODE_CONTEXT', 'Med review_ENROLLMENT'],
      verdict: 'BLOCKED — diagnosis codes excluded from Martin Pharmacy consent scope',
    },
    resolutionOptions: [
      'Member outreach to request expanded Martin Pharmacy consent',
      'Med review enrollment without diagnosis context (reduced effectiveness)',
      'Martin Pharmacy contacts Maria independently under their own NPP',
    ],
    hipaaMinimumNecessary: 'ENFORCED',
    auditId: 'AUDIT_20241115_144405_MARTIN PHARMACY_CONSENT_001',
  },
  consent_enforce_push: {
    agentId: 'CONSENT_ENFORCEMENT',
    action: 'SCOPE_BOUNDARY_ENFORCED',
    timestamp: '2024-11-15T14:42:19Z',
    memberId: 'MARIA_SD_001',
    proxyGrantor: 'Elena Redhawk',
    scopeViolationDetected: 'THIRD_PARTY_DISCLOSURE',
    agentAuthorityRevoked: 'CAREGIVER_INTELLIGENCE — third-party disclosure action',
    consentStateMonitoring: 'ACTIVE',
    realTimeRevocationCapable: true,
    auditId: 'AUDIT_20241115_144219_CONSENT_ENFORCE_001',
  },
  data_gov_push: {
    agentId: 'DATA_GOVERNANCE',
    action: 'PAYLOAD_CLEARED',
    timestamp: '2024-11-15T14:23:20Z',
    payloadsInspected: 47,
    piiMasked: 12,
    dataResidencyVerified: true,
    minimumNecessaryEnforced: true,
    fieldsRedacted: ['SSN', 'DOB_FULL', 'ADDRESS_FULL'],
    auditId: 'AUDIT_20241115_142320_DATAGOV_001',
  },
  audit_push: {
    agentId: 'AUDIT_AGENT',
    action: 'AUDIT_LEDGER_COMMITTED',
    timestamp: '2024-11-15T14:47:00Z',
    scenarioId: 'SCENARIO_MARIA_SD_001',
    totalDecisions: 71,
    agentsActivated: 8,
    governanceChecks: 8,
    governanceHonored: 8,
    interceptCount: 2,
    humanInterventions: 1,
    regulatoryDeadlinesMonitored: 1,
    consentEventsChecked: 4,
    graphUpdates: 14,
    resolutionTime: '47min',
    complianceScore: '100%',
    auditComplete: true,
    exportReady: true,
    auditLedgerRef: 'LEDGER_20241115_MARIA_SD_001',
    auditId: 'AUDIT_20241115_144700_AUDIT_001',
  },
  rhtp_mobile_push: {
    agentId: 'CARE_MANAGEMENT',
    action: 'RHTP_MOBILE_PUSH_DISPATCHED',
    timestamp: '2024-11-15T09:47:12Z',
    target: 'RHTP_MOBILE',
    memberId: 'MARIA_SD_001',
    channelOverride: {
      standardRouting: "PORTAL_WEB — Maria's learned preference (self-initiated Day 14, 2x/week)",
      overrideChannel: 'MOBILE_PUSH',
      overrideReason: 'PATIENT_SAFETY_THRESHOLD — DUPLICATE_THERAPY signal requires <15min response',
      triggerSignal: 'DUPLICATE_THERAPY: Lisinopril + Metformin same molecule, two active fills',
      latencyRequirement: '<15min — cannot wait for next portal login',
      policyRef: 'CHANNEL_INTEL.SAFETY.OVERRIDE.001',
      channelFamilyNote: "Mobile push within Maria's digital channel family — portal preference honored at channel-family level",
    },
    widgetPayload: [
      { priority: 1, type: 'SAFETY_ALERT', label: 'Metformin discontinued — continue Lisinopril 5mg', urgency: 'CRITICAL', action: 'GOT_IT', triggerSignal: 'DUPLICATE_THERAPY' },
      { priority: 2, type: 'ACTION_REQUIRED', label: 'A1C check — home kit, 7 days', urgency: 'HIGH', action: 'CONFIRM / RESCHEDULE', triggerSignal: 'A1C_OVERDUE_38D' },
      { priority: 3, type: 'CARE_UPDATE', label: 'Bennett County Health updated chart — postpartum rehab approved', urgency: 'HIGH', action: 'VIEW', triggerSignal: 'PROVIDER_WRITE_BACK' },
      { priority: 4, type: 'Med review_OPPORTUNITY', label: 'Medication review — Martin Pharmacy · 15 min · no cost', urgency: 'MEDIUM', action: 'ENROLL / REMIND_ME_LATER', triggerSignal: 'Med review_PARTIAL_CONSENT' },
      { priority: 5, type: 'FINANCIAL_SUMMARY', label: 'Covered pathway: $340–$480 · saves $2,400 vs out-of-network', urgency: 'LOW', action: 'VIEW_COST_BREAKDOWN', triggerSignal: 'FINANCIAL_SURPRISE_RISK' },
    ],
    suppressedSignals: [
      { signal: 'AUTH_RENEWAL_REMINDER', reason: 'FREQUENCY_LIMIT — member already received portal notification Day 32' },
      { signal: 'CAREGIVER_COORDINATION_PROMPT', reason: 'FREQUENCY_LIMIT — Elena notified separately via caregiver thread' },
    ],
    sessionContext: {
      day: 34,
      time: '09:47am',
      preferredWindow: 'Weekdays 9–11am',
      withinPreferredWindow: true,
      receptivityScore: 0.87,
    },
    deliveryMethod: 'RHTP_MOBILE_PUSH_NOTIFICATION',
    auditId: 'AUDIT_20241115_094712_RHTP_MOBILE_001',
  },
};
