// ─── orchestration/payloads.ts ────────────────────────────────────────────────
// JSON payload data shown in the OrchestrationFlowModal's right-panel viewer.

/* eslint-disable @typescript-eslint/no-explicit-any */

export const JSON_PAYLOADS: Record<string, object> = {
  signal_classification: {
    engineId: 'SIGNAL_CLASSIFICATION_ENGINE',
    action: 'CLASSIFICATION_COMPLETE',
    timestamp: '2024-11-15T14:22:57Z',
    memberId: 'MARIA_SD_001',
    signals: [
      { type: 'AUTH_EXPIRY', severity: 'HIGH', source: 'Claims System', detail: 'CAREGAP_HBA1C expiring T-4 days · HbA1c lab order · Bennett County Health · Winner Regional Healthcare' },
      { type: 'CARE_GAP', severity: 'HIGH', source: 'EHR/Quality Engine', detail: 'HbA1c gap open 45 days · last value 9.2% · Q4 SD Medicaid quality window closes Dec 31' },
      { type: 'BEHAVIORAL', severity: 'MEDIUM', source: 'Engagement Platform', detail: 'Portal logins 3x this week · receptivity 87% · caregiver stress elevated' },
    ],
    concurrentWindow: '30s',
    complexityScore: 'HIGH',
    contextFlags: ['CAREGIVER_RELATIONSHIP', 'DEPENDENT_RELATIONSHIP', 'Q4_SD Medicaid quality_WINDOW', 'POSTPARTUM_EPISODE_DAY427'],
    routingTarget: 'SUPER_ORCHESTRATION_CONTROLLER',
  },
  marketplace_query: {
    queryId: 'REGISTRY_QUERY_MARIA_SD_001_001',
    controllerAction: 'AGENT_MARKETPLACE_QUERY',
    timestamp: '2024-11-15T14:23:02Z',
    queryContext: {
      signalTypes: ['AUTH_EXPIRY', 'CARE_GAP', 'BEHAVIORAL'],
      memberContext: 'HIGH_RISK_POSTPARTUM_DAY427',
      relationshipContext: ['CAREGIVER', 'DEPENDENT'],
      operationalContext: ['Q4_SD Medicaid quality_WINDOW', 'TCOC_CEILING', 'AUTH_WINDOW'],
    },
    registryScanned: 31,
    matchedAgents: 8,
    unmatchedAgents: 23,
    coalitionAssembled: true,
    governanceOverlay: 'MANDATORY',
    matchedAgentRoster: [
      { rank: 1, agentId: 'CARE_AGENT_H1AB', agentName: 'Clinical Care Agent · H1AB Authorization', tier: 'FOUNDATION', matchScore: 0.97, confidenceScore: 0.94, matchReasons: ['AUTH_EXPIRY signal active', 'POSTPARTUM_EPISODE_DAY427 context', 'Q4_SD Medicaid quality_WINDOW operational flag'], assignedRole: 'PRIMARY_CARE_COORDINATOR' },
      { rank: 2, agentId: 'UTILIZATION_AGENT', agentName: 'Eligibility Management Agent', tier: 'FOUNDATION', matchScore: 0.95, confidenceScore: 0.91, matchReasons: ['AUTH_WINDOW context match', 'TCOC_CEILING exposure flag', 'Postpartum episode utilization pattern'], assignedRole: 'UTILIZATION_REVIEWER' },
      { rank: 3, agentId: 'FINANCIAL_INTELLIGENCE_AGENT', agentName: 'Financial Intelligence Agent', tier: 'FOUNDATION', matchScore: 0.93, confidenceScore: 0.89, matchReasons: ['TCOC_CEILING operational context', 'Q4_SD Medicaid quality_WINDOW financial exposure', 'HIGH_RISK member tier'], assignedRole: 'FINANCIAL_MODELER' },
      { rank: 4, agentId: 'SIGNAL_DISPOSITION_AGENT', agentName: 'Signal Disposition Agent', tier: 'FOUNDATION', matchScore: 0.91, confidenceScore: 0.88, matchReasons: ['Multi-signal triage required', 'AUTH_EXPIRY + CARE_GAP + BEHAVIORAL co-occurrence', 'Priority scoring active'], assignedRole: 'SIGNAL_TRIAGER' },
      { rank: 5, agentId: 'CAREGIVER_INTELLIGENCE_AGENT', agentName: 'Caregiver Intelligence Agent', tier: 'OPERATIONAL', matchScore: 0.88, confidenceScore: 0.85, matchReasons: ['CAREGIVER relationship context', 'Elena Redhawk proxy thread active', 'DEPENDENT relationship flag'], assignedRole: 'CAREGIVER_COORDINATOR' },
      { rank: 6, agentId: 'PROVIDER_ENABLEMENT_AGENT', agentName: 'Social / SDOH Agent', tier: 'OPERATIONAL', matchScore: 0.84, confidenceScore: 0.82, matchReasons: ['Eligibility gap detected', 'AUTH_EXPIRY requires provider validation', 'Network adequacy check needed'], assignedRole: 'PROVIDER_VALIDATOR' },
      { rank: 7, agentId: 'APPEALS_AGENT', agentName: 'Appeals & Grievance Agent', tier: 'OPERATIONAL', matchScore: 0.81, confidenceScore: 0.79, matchReasons: ['AUTH_EXPIRY creates appeal risk', 'POSTPARTUM_EPISODE_DAY427 clinical urgency', 'Q4_SD Medicaid quality_WINDOW deadline pressure'], assignedRole: 'APPEALS_HANDLER' },
      { rank: 8, agentId: 'Med review_AGENT', agentName: 'Medication Therapy Management Agent', tier: 'OPERATIONAL', matchScore: 0.78, confidenceScore: 0.76, matchReasons: ['BEHAVIORAL signal includes medication adherence', 'Postpartum medication reconciliation required', 'Duplicate therapy risk flag'], assignedRole: 'Med review_REVIEWER' },
    ],
    unmatchedAgentSample: [
      { agentId: 'DENTAL_BENEFITS_AGENT', agentName: 'Dental Benefits Agent', tier: 'OPERATIONAL', matchScore: 0.12, exclusionReason: 'No dental signal present; member context is postpartum/behavioral only' },
      { agentId: 'VISION_CARE_AGENT', agentName: 'Vision Clinical Care Agent', tier: 'OPERATIONAL', matchScore: 0.09, exclusionReason: 'Vision signal absent; no ophthalmology context in episode' },
      { agentId: 'MATERNITY_AGENT', agentName: 'Maternity & NICU Agent', tier: 'OPERATIONAL', matchScore: 0.04, exclusionReason: 'Member demographic mismatch; maternity context not applicable' },
      { agentId: 'BEHAVIORAL_CRISIS_AGENT', agentName: 'Behavioral Crisis Intervention Agent', tier: 'OPERATIONAL', matchScore: 0.31, exclusionReason: 'BEHAVIORAL signal present but below crisis threshold; standard care agent sufficient' },
      { agentId: 'TRANSPLANT_COORDINATION_AGENT', agentName: 'Transplant Coordination Agent', tier: 'SPECIALTY', matchScore: 0.07, exclusionReason: 'No transplant episode or organ waitlist context detected' },
      { agentId: 'PEDIATRIC_CARE_AGENT', agentName: 'Pediatric Clinical Care Agent', tier: 'OPERATIONAL', matchScore: 0.06, exclusionReason: 'Member age 67; adult care pathway applies' },
      { agentId: 'ONCOLOGY_AGENT', agentName: 'Oncology Navigation Agent', tier: 'SPECIALTY', matchScore: 0.14, exclusionReason: 'No active oncology diagnosis in member record; postpartum episode primary' },
      { agentId: 'WORKER_COMP_AGENT', agentName: "Worker's Compensation Agent", tier: 'OPERATIONAL', matchScore: 0.02, exclusionReason: 'No occupational injury claim; commercial health plan context only' },
      { agentId: 'SNOMED_CODING_AGENT', agentName: 'Clinical Coding Accuracy Agent', tier: 'QUALITY', matchScore: 0.22, exclusionReason: 'Coding review not triggered; AUTH_EXPIRY does not require recoding at this stage' },
      { agentId: 'FRAUD_WASTE_ABUSE_AGENT', agentName: 'Fraud, Waste & Abuse Detection Agent', tier: 'GOVERNANCE', matchScore: 0.18, exclusionReason: 'No anomaly pattern detected; claim history within expected variance for postpartum episode' },
    ],
    unmatchedAgentCount: 23,
    unmatchedSampleNote: 'Showing 10 of 23 unmatched agents. Remaining 13 excluded due to specialty mismatch, inactive contract status, or member demographic filters.',
  },
  graph_intel_push: {
    agentId: 'GRAPH_INTELLIGENCE',
    action: 'CONTEXT_ASSEMBLED',
    timestamp: '2024-11-15T14:23:00Z',
    memberId: 'MARIA_SD_001',
    graphNodes: 14,
    graphEdges: 17,
    identityConfidence: 0.97,
    resolvedRelationships: ['PARENT_OF → Sophia', 'CAREGIVER_FOR → Elena'],
    contextPackage: 'ORCHESTRATION_CONTEXT_001',
    auditId: 'AUDIT_20241115_142300_GRAPH_001',
  },
  identity_push: {
    agentId: 'IDENTITY_RESOLUTION',
    action: 'GOLDEN_RECORD_COMMITTED',
    timestamp: '2024-11-15T14:23:08Z',
    memberId: 'MARIA_SD_001',
    sourcesReconciled: 4,
    conflictsResolved: 3,
    goldenRecordId: 'GR_MARIA_SD_001',
    confidence: 0.97,
    authoritativeSource: 'CLAIMS',
    auditId: 'AUDIT_20241115_142308_IDENTITY_001',
  },
  consent_push: {
    agentId: 'CONSENT_AGENT',
    action: 'CONSENT_GATE_OPENED',
    timestamp: '2024-11-15T14:23:15Z',
    memberId: 'MARIA_SD_001',
    consentScope: 'FULL',
    proxyConsentFor: 'Elena Redhawk',
    proxyScope: ['MEDICATION_MGMT', 'APPT_COORDINATION'],
    consentGateStatus: 'OPEN',
    boundaryEnforced: true,
    auditId: 'AUDIT_20241115_142315_CONSENT_001',
  },
  person_state_push: {
    agentId: 'PERSON_STATE_INTELLIGENCE',
    action: 'STATE_PROFILE_ASSEMBLED',
    timestamp: '2024-11-15T14:23:18Z',
    memberId: 'MARIA_SD_001',
    behavioralState: 'ENGAGED',
    portalEngagement: '3 logins this week',
    receptivityScore: 0.87,
    communicationFatigue: 'LOW',
    lifeEventSignals: ['CAREGIVER_STRESS_ELEVATED', 'DEPENDENT_CARE_GAP'],
    recommendedChannel: 'PORTAL',
    recommendedTiming: '10am — peak engagement window',
    auditId: 'AUDIT_20241115_142318_PERSON_001',
  },
  care_push: {
    agentId: 'CARE_MANAGEMENT',
    action: 'AUTH_EVIDENCE_SUBMITTED',
    timestamp: '2024-11-15T14:31:08Z',
    memberId: 'MARIA_SD_001',
    authorizationId: 'CAREGAP_HBA1C',
    procedureCode: 'HbA1c',
    procedureDescription: 'HbA1c lab — transthoracic',
    expiryDaysRemaining: 4,
    clinicalEvidence: {
      diagnosisCodes: ['I25.10', 'E11.9'],
      primaryDiagnosis: 'Chronic ischemic heart disease, unspecified',
      supportingRecords: 3,
      medicalNecessityBasis: 'Active postpartum episode Day 427 — ongoing monitoring required per SD Medicaid LCD L38779',
      priorAuthHistory: 'AUTH_000 approved 2024-08-15 — same procedure, same provider',
    },
    sdohBarrierResolved: {
      barrierType: 'TRANSPORT_PROBABLE',
      resolution: 'Home lab kit dispatched 2024-11-14 — eliminates clinic transport requirement',
      evidence: '2 missed appointments in 12 months — same zip code pattern',
    },
    governanceCheck: 'PASSED',
    auditId: 'AUDIT_20241115_143108_CARE_001',
  },
  provider_push: {
    agentId: 'PROVIDER_ENABLEMENT',
    action: 'CREDENTIALING_RENEWAL_INITIATED',
    timestamp: '2024-11-15T14:45:22Z',
    providerId: 'NPI_1234567890',
    providerName: 'Bennett County Health',
    specialty: 'Cardiology',
    facility: 'Bennett County Health',
    eligibilityStatus: 'EXPIRING',
    renewalDeadlineDays: 21,
    renewalDeadlineDate: '2024-12-06',
    activeEpisodesAtRisk: 12,
    episodesProtectedByRenewal: 12,
    renewalWorkflow: 'AUTOMATED — no human intervention required',
    eligibilitySystemRef: 'CRED_RENEWAL_20241115_001',
    networkAdequacyImpact: 'NONE — renewal initiated before lapse',
    auditId: 'AUDIT_20241115_144522_PROV_001',
  },
  utilization_push: {
    agentId: 'UTILIZATION_MANAGEMENT',
    action: 'AUTH_RECORD_UPDATED',
    timestamp: '2024-11-15T14:31:08Z',
    authorizationId: 'CAREGAP_HBA1C',
    procedureCode: 'HbA1c',
    clinicalGuidelineRef: 'SD Medicaid_LCD_L38779',
    medicalNecessityVerdict: 'APPROVED — criteria met',
    criteriaApplied: [
      'Active postpartum episode with documented prior auth history',
      'Diagnosis I25.10 meets echocardiography indication threshold',
      'Day 34 of 90-day episode — monitoring interval appropriate',
    ],
    payerSystemUpdate: 'SUBMITTED',
    authCycleTimeDays: 0.3,
    previousCycleTimeDays: 8.2,
    improvementPct: 96,
    mlrExposureReduced: true,
    auditId: 'AUDIT_20241115_143108_UTIL_001',
  },
  appeals_push: {
    agentId: 'APPEALS_GRIEVANCES',
    action: 'HOLD_FOR_HUMAN_REVIEW',
    timestamp: '2024-11-15T14:31:22Z',
    appealId: 'APPEAL_20241115_001',
    appealType: 'CLINICAL_NECESSITY_DETERMINATION',
    interceptedBy: 'POLICY_BOUNDARY',
    policyTriggered: 'SD Medicaid.APPEAL.AUTO.THRESHOLD.001',
    reason: 'Clinical necessity determination for postpartum care procedure exceeds automated authority — physician review required',
    automatedActionAttempted: 'DISPATCH_APPEAL_WITHOUT_PHYSICIAN_SIGN_OFF',
    disposition: 'HOLD_FOR_HUMAN_REVIEW',
    reviewerNotified: 'Dr. K. Patel — Medical Director',
    reviewerNotifiedAt: '2024-11-15T14:31:25Z',
    deadlineHoursRemaining: 68,
    regulatoryDeadline: 'SD Medicaid 72-hour prior auth review standard',
    contextPackageAssembled: true,
    contextPackageRef: 'APPEAL_CTX_20241115_001',
    auditId: 'AUDIT_20241115_143122_APPEALS_001',
  },
  financial_push: {
    agentId: 'FINANCIAL_INTELLIGENCE',
    action: 'MEMBER_PORTAL_UPDATED',
    timestamp: '2024-11-15T14:38:00Z',
    memberId: 'MARIA_SD_001',
    calculationBasis: {
      planYear: 2024,
      deductibleMet: 1200,
      deductibleRemaining: 300,
      oopMaxRemaining: 1840,
      procedureCode: 'HbA1c',
      networkStatus: 'IN_NETWORK — Winner Regional Healthcare',
    },
    oopLiabilityRange: { min: 340, max: 480, currency: 'USD', confidence: 'HIGH' },
    outOfNetworkExposureAvoided: 2400,
    referralInitiated: 'Dr. Sarah Kim — in-network cardiologist',
    costSummarySent: true,
    costSummaryChannel: 'MEMBER_PORTAL — widget pushed',
    benefitsEngineRef: 'BENEFITS_CALC_20241115_001',
    financialSurpriseRisk: 'ELIMINATED',
    auditId: 'AUDIT_20241115_143800_FIN_001',
  },
  caregiver_push: {
    agentId: 'CAREGIVER_INTELLIGENCE',
    action: 'BLOCKED_BY_GOVERNANCE',
    timestamp: '2024-11-15T14:42:19Z',
    attemptedAction: 'SHARE_MEDICATION_LIST_THIRD_PARTY',
    blockedBy: 'POLICY_BOUNDARY',
    policyTriggered: 'CONSENT.PROXY.SCOPE.BOUNDARY.001',
    proxyGrantor: 'Elena Redhawk',
    proxyConsentScope: ['MEDICATION_MGMT', 'APPT_COORDINATION'],
    scopeExceeded: 'THIRD_PARTY_DISCLOSURE — medication list to external care coordinator',
    actionWithinScope: {
      inrMonitoringInitiated: true,
      lisinoprilInteractionFlagged: true,
      elenaThreadUpdated: true,
      note: "A1C monitoring and Lisinopril flag actioned within Elena's granted proxy scope",
    },
    resolution: 'Elena must grant expanded scope OR care coordinator contacts Maria directly under separate NPP',
    auditId: 'AUDIT_20241115_144219_CARE_001',
  },
  finops_push: {
    agentId: 'FINOPS_AGENT',
    action: 'COST_CAPTURE_COMPLETE',
    timestamp: '2024-11-15T14:48:00Z',
    scenarioId: 'SCENARIO_MARIA_SD_001',
    interventionCosts: {
      estimated: 2840,
      actual: 2650,
      variance: -190,
      variancePct: -6.7,
      underBudgetReason: 'Automated auth renewal eliminated 2 manual review cycles',
    },
    costAvoidance: {
      total: 18400,
      breakdown: {
        avoidedReadmission: 14200,
        manualProcessingEliminated: 2800,
        duplicateTherapyResolved: 1400,
      },
    },
    tcocImpact: -0.003,
    interventionType: 'AUTH_RENEWAL + CARE_GAP_CLOSURE + DUPLICATE_THERAPY_RESOLUTION',
    auditId: 'AUDIT_20241115_144800_FINOPS_001',
  },
  h1ab_push: {
    agentId: 'CARE_MANAGEMENT',
    action: 'H1AB_CONTEXT_ENRICHED',
    timestamp: '2024-11-15T14:49:12Z',
    target: 'H1ab — Sarah Johnson queue',
    careManagerId: 'CM_SARAH_JOHNSON',
    memberId: 'MARIA_SD_001',
    contextUpgrade: {
      previousContextAge: '47_DAYS',
      previousContextStatus: 'STALE — missed transport barrier, family context absent',
      newContextFreshness: 'REAL_TIME',
      updateType: 'FULL_ENRICHMENT',
    },
    criticalBlockers: [
      {
        type: 'TRANSPORT_BARRIER',
        severity: 'PROBABLE',
        evidence: '2 missed appointments in 12 months — same zip code pattern',
        systemResponse: 'Home lab kit dispatched 2024-11-14 — transport barrier pre-resolved',
        careManagerAction: 'Confirm home kit receipt at 10am call — do NOT book clinic appointment',
        fallback: 'Telehealth + mobile phlebotomy available if kit declined',
        graphQuery: 'TRANSPORT_BARRIER -[:BLOCKS]-> HbA1c_CARE_GAP — confirmed via Cypher',
      },
    ],
    enrichedContext: {
      sdohBarriers: ['TRANSPORT_PROBABLE', 'FINANCIAL_ELEVATED', 'CAREGIVER_BURDEN_HIGH'],
      familyContext: {
        sofia: '6 open care gaps — dependent coordination required',
        elena: 'Lisinopril/A1C elevated — proxy thread active — consent scope LIMITED',
      },
      activeSignals: 4,
      interventionsDispatched: 8,
      careGapsAddressed: ['HbA1c_45d — home kit dispatched'],
      authStatus: 'CAREGAP_HBA1C renewal evidence submitted — cycle time 0.3d',
      episodeContext: 'Postpartum Episode — Day 34 of 90-day window',
    },
    outreachBrief: {
      scheduledTime: '10:00am',
      rationale: 'Peak engagement window — portal signals confirm receptivity 87%',
      scriptType: 'BARRIER_AWARE — transport blocker pre-resolved',
      openingLine: '"Hi Maria, I\'m calling to confirm your home lab kit arrived"',
      doNotMention: 'Clinic appointment — transport barrier makes this likely to fail',
    },
    auditId: 'AUDIT_20241115_144912_H1AB_001',
  },
  dr_chen_cds_hook: {
    hookType: 'appointment-booked',
    fhirVersion: 'R4',
    hookFiredAt: '2024-11-15T08:00:00Z',
    deliveryLatency: '<200ms',
    provider: 'Bennett County Health · NPI: 1234567890 · Cardiology',
    system: 'Bennett County Health EHR — Epic',
    patientId: 'MARIA_SD_001',
    appointmentDate: '2024-11-15T10:00:00Z',
    alertCards: [
      { priority: 1, type: 'DUPLICATE_THERAPY', urgency: 'HIGH', detail: 'Lisinopril 5mg (CVS #4821) + Metformin 5mg (Walgreens #7734) — same molecule, two active fills', inrStatus: 'OVERDUE — 38 days since last check', suggestedActions: ['DISCONTINUE one fill', 'ORDER A1C', 'ENROLL Med review (partial consent)'] },
      { priority: 2, type: 'CARE_GAP_HBA1C', urgency: 'MEDIUM', detail: 'Last HbA1c: 9.2% — 47 days remaining in Q4 SD Medicaid quality measurement window', barrierNote: 'Transport barrier pre-resolved — home lab kit dispatched 2024-11-14', suggestedActions: ['ORDER LAB — home kit active, no clinic visit needed'] },
      { priority: 3, type: 'AUTH_PRE_APPROVED', urgency: 'INFO', detail: 'CAREGAP_HBA1C renewal pre-assembled — HbA1c lab order · SD Medicaid LCD L38779 · cycle time 0.3d', suggestedActions: ['ATTACH to postpartum rehab referral'] },
    ],
    deliveryMethod: 'CDS_HOOKS_FHIR_R4',
  },
  policy_intercept_appeals: {
    agentId: 'POLICY_BOUNDARY',
    action: 'INTERCEPT',
    timestamp: '2024-11-15T14:31:22Z',
    interceptedAgent: 'APPEALS_GRIEVANCES',
    interceptedAction: 'AUTOMATED_APPEAL_DISPATCH',
    policyTriggered: 'SD Medicaid.APPEAL.AUTO.THRESHOLD.001',
    reason: 'Clinical necessity determination exceeds automated authority',
    disposition: 'HOLD_FOR_HUMAN_REVIEW',
    reviewerNotified: 'Dr. K. Patel',
    deadlineHoursRemaining: 68,
    contextPackageAssembled: true,
    auditId: 'AUDIT_20241115_143122_GOV_001',
  },
  policy_intercept_caregiver: {
    agentId: 'POLICY_BOUNDARY',
    action: 'INTERCEPT',
    timestamp: '2024-11-15T14:42:19Z',
    interceptedAgent: 'CAREGIVER_INTELLIGENCE',
    interceptedAction: 'SHARE_MEDICATION_LIST_THIRD_PARTY',
    policyTriggered: 'CONSENT.PROXY.SCOPE.BOUNDARY.001',
    proxyConsentScope: ['MEDICATION_MGMT', 'APPT_COORDINATION'],
    scopeExceeded: 'THIRD_PARTY_DISCLOSURE',
    resolution: 'Elena must grant expanded scope OR coordinator contacts directly',
    auditId: 'AUDIT_20241115_144219_GOV_001',
  },
  policy_intercept_pharmacy: {
    agentId: 'POLICY_BOUNDARY',
    action: 'INTERCEPT',
    timestamp: '2024-11-15T14:44:05Z',
    interceptedAgent: 'CARE_MANAGEMENT',
    interceptedAction: 'SHARE_POSTPARTUM_EPISODE_CONTEXT_MARTIN PHARMACY',
    policyTriggered: 'CONSENT.DOMAIN.BOUNDARY.002',
    consentDomain: 'MARTIN PHARMACY',
    consentScope: 'LIMITED — fill history only',
    scopeExceeded: 'DIAGNOSIS_CODES_AND_EPISODE_CONTEXT',
    attemptedAction: 'Share postpartum episode context with Martin Pharmacy for Medication Therapy Management enrollment',
    domainCheck: {
      domain: 'MARTIN PHARMACY',
      grantedScope: ['FILL_HISTORY'],
      requestedScope: ['DIAGNOSIS_CODES', 'EPISODE_CONTEXT', 'Med review_ENROLLMENT'],
      verdict: 'BLOCKED — diagnosis codes excluded from Martin Pharmacy consent scope',
    },
    resolutionOptions: [
      'Member outreach to request expanded Martin Pharmacy consent',
      'Med review enrollment without diagnosis context (reduced effectiveness)',
      'Martin Pharmacy contacts Maria independently under their own NPP',
    ],
    hipaaMinimumNecessary: 'ENFORCED',
    auditId: 'AUDIT_20241115_144405_MARTIN PHARMACY_CONSENT_001',
  },
  consent_enforce_push: {
    agentId: 'CONSENT_ENFORCEMENT',
    action: 'SCOPE_BOUNDARY_ENFORCED',
    timestamp: '2024-11-15T14:42:19Z',
    memberId: 'MARIA_SD_001',
    proxyGrantor: 'Elena Redhawk',
    scopeViolationDetected: 'THIRD_PARTY_DISCLOSURE',
    agentAuthorityRevoked: 'CAREGIVER_INTELLIGENCE — third-party disclosure action',
    consentStateMonitoring: 'ACTIVE',
    realTimeRevocationCapable: true,
    auditId: 'AUDIT_20241115_144219_CONSENT_ENFORCE_001',
  },
  data_gov_push: {
    agentId: 'DATA_GOVERNANCE',
    action: 'PAYLOAD_CLEARED',
    timestamp: '2024-11-15T14:23:20Z',
    payloadsInspected: 47,
    piiMasked: 12,
    dataResidencyVerified: true,
    minimumNecessaryEnforced: true,
    fieldsRedacted: ['SSN', 'DOB_FULL', 'ADDRESS_FULL'],
    auditId: 'AUDIT_20241115_142320_DATAGOV_001',
  },
  audit_push: {
    agentId: 'AUDIT_AGENT',
    action: 'AUDIT_LEDGER_COMMITTED',
    timestamp: '2024-11-15T14:47:00Z',
    scenarioId: 'SCENARIO_MARIA_SD_001',
    totalDecisions: 71,
    agentsActivated: 8,
    governanceChecks: 8,
    governanceHonored: 8,
    interceptCount: 2,
    humanInterventions: 1,
    regulatoryDeadlinesMonitored: 1,
    consentEventsChecked: 4,
    graphUpdates: 14,
    resolutionTime: '47min',
    complianceScore: '100%',
    auditComplete: true,
    exportReady: true,
    auditLedgerRef: 'LEDGER_20241115_MARIA_SD_001',
    auditId: 'AUDIT_20241115_144700_AUDIT_001',
  },
  rhtp_mobile_push: {
    agentId: 'CARE_MANAGEMENT',
    action: 'RHTP_MOBILE_PUSH_DISPATCHED',
    timestamp: '2024-11-15T09:47:12Z',
    target: 'RHTP_MOBILE',
    memberId: 'MARIA_SD_001',
    channelOverride: {
      standardRouting: "PORTAL_WEB — Maria's learned preference (self-initiated Day 14, 2x/week)",
      overrideChannel: 'MOBILE_PUSH',
      overrideReason: 'PATIENT_SAFETY_THRESHOLD — DUPLICATE_THERAPY signal requires <15min response',
      triggerSignal: 'DUPLICATE_THERAPY: Lisinopril + Metformin same molecule, two active fills',
      latencyRequirement: '<15min — cannot wait for next portal login',
      policyRef: 'CHANNEL_INTEL.SAFETY.OVERRIDE.001',
      channelFamilyNote: "Mobile push within Maria's digital channel family — portal preference honored at channel-family level",
    },
    widgetPayload: [
      { priority: 1, type: 'SAFETY_ALERT', label: 'Metformin discontinued — continue Lisinopril 5mg', urgency: 'CRITICAL', action: 'GOT_IT', triggerSignal: 'DUPLICATE_THERAPY' },
      { priority: 2, type: 'ACTION_REQUIRED', label: 'A1C check — home kit, 7 days', urgency: 'HIGH', action: 'CONFIRM / RESCHEDULE', triggerSignal: 'A1C_OVERDUE_38D' },
      { priority: 3, type: 'CARE_UPDATE', label: 'Bennett County Health updated chart — postpartum rehab approved', urgency: 'HIGH', action: 'VIEW', triggerSignal: 'PROVIDER_WRITE_BACK' },
      { priority: 4, type: 'Med review_OPPORTUNITY', label: 'Medication review — Martin Pharmacy · 15 min · no cost', urgency: 'MEDIUM', action: 'ENROLL / REMIND_ME_LATER', triggerSignal: 'Med review_PARTIAL_CONSENT' },
      { priority: 5, type: 'FINANCIAL_SUMMARY', label: 'Covered pathway: $340–$480 · saves $2,400 vs out-of-network', urgency: 'LOW', action: 'VIEW_COST_BREAKDOWN', triggerSignal: 'FINANCIAL_SURPRISE_RISK' },
    ],
    suppressedSignals: [
      { signal: 'AUTH_RENEWAL_REMINDER', reason: 'FREQUENCY_LIMIT — member already received portal notification Day 32' },
      { signal: 'CAREGIVER_COORDINATION_PROMPT', reason: 'FREQUENCY_LIMIT — Elena notified separately via caregiver thread' },
    ],
    sessionContext: {
      day: 34,
      time: '09:47am',
      preferredWindow: 'Weekdays 9–11am',
      withinPreferredWindow: true,
      receptivityScore: 0.87,
    },
    deliveryMethod: 'RHTP_MOBILE_PUSH_NOTIFICATION',
    auditId: 'AUDIT_20241115_094712_RHTP_MOBILE_001',
  },
};
