<#
.SYNOPSIS
  .env.local writer. Reads env-templates.json; merges/writes env files.
  One responsibility: safe, idempotent env file management. No UI, no installs.
#>

function Write-EnvFile {
  param(
    [string]    $Path,
    [hashtable] $Vars,
    [switch]    $Merge    # if set, preserve existing keys not in $Vars
  )

  $existing = @{}
  if ($Merge -and (Test-Path $Path)) {
    $existing = Read-EnvFile $Path
  }

  $merged = @{}
  foreach ($k in $existing.Keys) { $merged[$k] = $existing[$k] }
  foreach ($k in $Vars.Keys)     { $merged[$k] = $Vars[$k] }

  $lines = @("# Generated by RHTP installer — $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
  foreach ($k in ($merged.Keys | Sort-Object)) {
    $lines += "$k=$($merged[$k])"
  }

  $lines | Set-Content -Path $Path -Encoding UTF8
  Write-Host "  Wrote: $Path ($($merged.Count) vars)"
}

function Read-EnvFile {
  param([string] $Path)
  $result = @{}
  if (-not (Test-Path $Path)) { return $result }
  Get-Content $Path | ForEach-Object {
    $line = $_.Trim()
    if ($line -and -not $line.StartsWith('#') -and $line -match '^([^=]+)=(.*)$') {
      $result[$Matches[1].Trim()] = $Matches[2].Trim()
    }
  }
  return $result
}

function Build-EnvVars {
  param(
    [string]    $DataDir,
    [string[]]  $Components,
    [string]    $Mode,
    [hashtable] $UserInputs   # keyed by var name; values from wizard form
  )
  # Load templates
  $tmpl = Get-Content "$DataDir\env-templates.json" -Raw | ConvertFrom-Json

  $vars = @{}

  # ── RHTP ──────────────────────────────────────────────────────────────────
  if ($Components -contains 'rhtp') {
    Merge-Template $tmpl.rhtp.$Mode $vars
  }

  # ── CMS ───────────────────────────────────────────────────────────────────
  if ($Components -contains 'cms') {
    Merge-Template $tmpl.cms.$Mode $vars

    # Auto-generate secrets if not already set
    foreach ($k in @('SESSION_SECRET','WEBHOOK_SHARED_SECRET')) {
      if (-not $vars[$k] -or $vars[$k] -eq '__GENERATE__') {
        $vars[$k] = New-RandomSecret 32
      }
    }

    # Production: WSO2 fields from user input
    if ($Mode -eq 'production') {
      foreach ($prop in $tmpl.cms_wso2.PSObject.Properties) {
        $val = $UserInputs[$prop.Name]
        if ($val) { $vars[$prop.Name] = $val }
      }
    }
  }

  # ── Golden Thread / LLM ───────────────────────────────────────────────────
  if ($Components -contains 'golden-thread' -and $Mode -eq 'production') {
    Set-LlmVars $tmpl $UserInputs $vars
  }

  # ── Override any remaining __USER_INPUT__ / __GENERATE__ placeholders ─────
  foreach ($k in @($vars.Keys)) {
    if ($vars[$k] -eq '__GENERATE__')   { $vars[$k] = New-RandomSecret 32 }
    if ($vars[$k] -eq '__USER_INPUT__') { $vars.Remove($k) }
  }

  return $vars
}

function Build-PaEnvVars {
  param(
    [string]    $DataDir,
    [string]    $Mode,
    [hashtable] $UserInputs
  )
  $tmpl = Get-Content "$DataDir\env-templates.json" -Raw | ConvertFrom-Json
  $vars = @{}
  Merge-Template $tmpl.pa.$Mode $vars

  if ($Mode -eq 'production') {
    Set-LlmVars $tmpl $UserInputs $vars
  }

  return $vars
}

# ── Private helpers ───────────────────────────────────────────────────────────

function Merge-Template {
  param([object] $Template, [hashtable] $Target)
  if (-not $Template) { return }
  foreach ($prop in $Template.PSObject.Properties) {
    $Target[$prop.Name] = $prop.Value
  }
}

function Set-LlmVars {
  param([object] $Tmpl, [hashtable] $UserInputs, [hashtable] $Target)
  $provider = $UserInputs['LLM_PROVIDER']   # 'groq' or 'openai'
  if ($provider -eq 'groq'   -and $UserInputs['GROQ_API_KEY'])   { $Target['GROQ_API_KEY']   = $UserInputs['GROQ_API_KEY'] }
  if ($provider -eq 'openai' -and $UserInputs['OPENAI_API_KEY']) { $Target['OPENAI_API_KEY'] = $UserInputs['OPENAI_API_KEY'] }
}

function New-RandomSecret {
  param([int] $Length = 32)
  $bytes = [byte[]]::new($Length)
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
  return [Convert]::ToBase64String($bytes).Substring(0, $Length) -replace '[+/=]', 'x'
}
